version: '3.8'

services:
  room-mysql-container:
    image: mysql:8.0
    container_name: room-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: infra
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    networks:
      - room-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10



  room-spring-container:
    image: nniinjjii/roommate:latest
    container_name: room-spring-container
    depends_on:
      room-mysql-container:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - room-network

volumes:
  mysql-data:

networks:
  room-network: