version: '3.8'

services:
  room-mysql-container:
    image: mysql:8.0
    container_name: room-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: infra
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    networks:
      - room-network

  room-spring-container:
    build: .
    container_name: room-spring-container
    depends_on:
      - room-mysql-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - room-network

volumes:
  mysql-data:

networks:
  room-network: