name: roomMate Github Actions CI/CD

on:
  push:
    branches: ["develop"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Naming jar file
        run: mv ./target/*.jar ./target/roommate.jar

      - name: Check jar file
        run: ls ./target

      - uses: actions/upload-artifact@v4
        with:
          name: roommate
          path: ./target/*.jar

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: roommate

      - name: Deploy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "*.jar"
          target: "/home/ubuntu/roommate"

      - name: Execute deployment script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/roommate/deploy
            mv /home/ubuntu/roommate/*.jar /home/ubuntu/roommate/deploy/roommate.jar
            sudo fuser -k -n tcp 8080 || true
            cd /home/ubuntu/roommate/deploy
            nohup java -jar roommate.jar > ./output.log 2>&1 &
